### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file

### ISSUE THREAD

**Issue by Pitsyjulio** [sschwartzman/newrelic-unix-plugin#13]
Hello. 

i am trying to run your plug in  a solaris machine  version  Oracle Solaris 10 9/10 s10s_u9wos_14a SPARC but when i run the command to start  i can see the follow error on the log file.

Plugin location: /export/home/lf968093/newrelic-unix-plugin-master
Java location: /usr/bin/java
Java version: java version "1.5.0_32"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_32-b05)
Java HotSpot(TM) Server VM (build 1.5.0_32-b05, mixed mode)
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:56)

could you please help me to solve it?

**Comment by sschwartzman** [comment]
The plugin requires Java 1.6 and above:
https://github.com/sschwartzman/newrelic-unix-plugin#requirements

If you have Java 1.6 or above elsewhere on that machine, set PLUGIN_JAVA in pluginctl.sh to point at it (see step 5: https://github.com/sschwartzman/newrelic-unix-plugin#installation--usage-overview).
