### ISSUE TITLE
AIX Proxy Issue

### ISSUE THREAD

**Issue by miguelmattos** [sschwartzman/newrelic-unix-plugin#40]
Hi there.

I have a customer that is trying to install the newrelic-unix-plugin on his server, but he's experienced some issues when setting up the proxy settings.

Every time he tries to start the "agent", he gets this error message:

<[2017-06-16 12:17:53,679] ERROR com.newrelic.metrics.publish.binding.Request - An error occurred communicating with the New Relic service 
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" 
at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:1674) ~[na:1.6.0] 
at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:12) ~[na:6.0 build_20130410] 
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1031) ~[na:1.6.0] 
at com.ibm.net.ssl.www2.protocol.https.b.getOutputStream(b.java:96) ~[na:6.0 build_20130410] 
at com.newrelic.metrics.publish.binding.Request.deliver(Request.java:106) ~[metrics_publish-2.0.1.jar:2.0.1 September 2 2014] 
at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:213) [metrics_publish-2.0.1.jar:2.0.1 September 2 2014] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0] 
at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0] 
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0] 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0] 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0] 
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0] 
at java.lang.Thread.run(Thread.java:738) [na:1.6.0] >

Maybe we need to configure some "Certificated Authority" because he got this message too.

<Caused by: java.security.cert.CertPathValidatorException: The certificate issued by EMAILADDRESS=intellojas@multivarejogpa.com.br, CN=10.141.6.11, OU=TI, O=Companhia Brasileira de Distribuicao, L=Sao Paulo, ST=Sao Paulo, C=BR is not trusted >

Here is the newrelic.json configuration.

<cbdx08:/home/gtouser/NewRelic/newrelic_unix_plugin/config>more newrelic.json 
{ 
"license_key": "e2b70a2fd2a4f5ab0805b93fc2eff005ec60afcf", 
"log_level": "info", 
"log_file_name": "newrelic_plugin.log", 
"log_file_path": "logs", 
"log_limit_in_kbytes": 10000 , 
"proxy_host": "10.141.6.11" , 
"proxy_port": "80" , 
} 
>

Looking forward to your comments.

Thanks in advance.

Miguel.

**Comment by sschwartzman** [comment]
Hi Miguel,

That it says "HTTP/1.1 407 Proxy Authentication Required" tells me that the proxy requires user/password credentials added to the config file.

Per the [README](https://github.com/sschwartzman/newrelic-unix-plugin#proxy-configuration), the settings are:
```
  "proxy_username": "my_user",
  "proxy_password": "my_password"
```

Can you add those and try it again?

**Comment by miguelmattos** [comment]
Ok, Seth.

Thanks for your quick answer!

I'll try it right now.

I'll give you a feedback ASAP.

Thx!

Miguel.

2017-06-16 12:32 GMT-03:00 Seth Schwartzman <notifications@github.com>:

**Comment by miguelmattos** [comment]
Hey, Seth.

We just tried to use "proxy_username" and "proxy_password" settings, and we
got the same error message.

Any other suggestion?

Thx!

2017-06-16 13:13 GMT-03:00 Miguel Mattos <miguelmattos@gmail.com>:

**Comment by miguelmattos** [comment]
Hi, Seth.

I'll appreciate your comments when you be able:

"We've tried to use "proxy_username" and "proxy_password" settings, and we got the same error message.

Any other suggestion?"

Thanks a lot!

**Comment by sschwartzman** [comment]
Since these problems are within the Java Plugin SDK (https://github.com/newrelic-platform/metrics_publish_java), it's not something I can fix if it's not working. I can take a look at their config files and logs to see if its something else, but if there's nothing glaring there, we'll need you to work with the people that own that repo.

Can you attach their config files and log files to this issue?
