### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by TechParmar** [sschwartzman/newrelic-unix-plugin#51]
Running on RHEL 5 with JRE 1.6.

Getting this issue. when running the agent. 

[2018-04-19 16:14:23,018] DEBUG com.newrelic.metrics.publish.Runner - Ending poll cycle for agent: 'sa2.scprod.businesswire.com'
[2018-04-19 16:14:23,098] DEBUG com.newrelic.metrics.publish.binding.Request - Sending JSON: {"components":[{"guid":"com.chocolatefactory.newrelic.plugins.unix","duration":60,"metrics":{"Component\/Disk\/xvda1\/Used[kb]":[62367.0,1,62367.0,62367.0,3.88964275E9],"Component\/Disk\/tmpfs\/Total[kb]":[8198764.0,1,8198764.0,8198764.0,6.7219732E13],"Component\/Disk\/tmpfs\/Used[kb]":[0.0,1,0.0,0.0,0.0],"Component\/Disk\/tmpfs\/Used[percent]":[0.0,1,0.0,0.0,0.0],"Component\/Disk\/xvda1\/Total[kb]":[1.0824416E7,1,1.0824416E7,1.0824416E7,1.17167983E14],"Component\/VmstatTotals\/nice user cpu ticks[ticks]":[1.1042497E7,1,1.1042497E7,1.1042497E7,1.21936739E14]},"name":"sa2.scprod.businesswire.com"}],"agent":{"host":"host","pid":0,"version":"3.6.4"}}
[2018-04-19 16:14:23,102] DEBUG com.newrelic.metrics.publish.binding.Context - Metric service url: https://platform-api.newrelic.com/platform/v1/metrics
[2018-04-19 16:14:24,040] ERROR com.newrelic.metrics.publish.binding.Request - An error occurred communicating with the New Relic service
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at com.sun.net.ssl.internal.ssl.InputRecord.handleUnknownRecord(InputRecord.java:652) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:484) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:863) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215) ~[na:1.6]
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199) ~[na:1.6]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434) ~[na:1.6]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166) ~[na:1.6]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1031) ~[na:1.6.0_45]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230) ~[na:1.6]
	at com.newrelic.metrics.publish.binding.Request.deliver(Request.java:106) ~[metrics_publish-2.0.1.jar:2.0.1 September 2 2014]
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:213) [metrics_publish-2.0.1.jar:2.0.1 September 2 2014]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_45]
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0_45]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

**Comment by sschwartzman** [comment]
Please try the new plugin (which reports to NR Insights) and report any issues there: https://github.com/newrelic-experts/unix-infra-monitor
